//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ViajesOnTour
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int PROCEDURE_PRUEBA(string pARAM_USR, string pARAM_PASS)
        {
            var pARAM_USRParameter = pARAM_USR != null ?
                new ObjectParameter("PARAM_USR", pARAM_USR) :
                new ObjectParameter("PARAM_USR", typeof(string));
    
            var pARAM_PASSParameter = pARAM_PASS != null ?
                new ObjectParameter("PARAM_PASS", pARAM_PASS) :
                new ObjectParameter("PARAM_PASS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_PRUEBA", pARAM_USRParameter, pARAM_PASSParameter);
        }
    }
}
